/** Çeviri için yaygın ISO 639-1 kodları (Google Translate uyumlu) */
export const TARGET_LANGUAGES: { code: string; label: string }[] = [
  { code: "tr", label: "Türkçe" },
  { code: "en", label: "İngilizce" },
  { code: "de", label: "Almanca" },
  { code: "fr", label: "Fransızca" },
  { code: "es", label: "İspanyolca" },
  { code: "it", label: "İtalyanca" },
  { code: "pt", label: "Portekizce" },
  { code: "nl", label: "Hollandaca" },
  { code: "pl", label: "Lehçe" },
  { code: "ru", label: "Rusça" },
  { code: "uk", label: "Ukraynaca" },
  { code: "ar", label: "Arapça" },
  { code: "fa", label: "Farsça" },
  { code: "hi", label: "Hintçe" },
  { code: "ja", label: "Japonca" },
  { code: "ko", label: "Korece" },
  { code: "zh-CN", label: "Çince (Basitleştirilmiş)" },
  { code: "th", label: "Tayca" },
  { code: "vi", label: "Vietnamca" },
  { code: "id", label: "Endonezce" },
  { code: "ms", label: "Malayca" },
  { code: "sv", label: "İsveççe" },
  { code: "da", label: "Danca" },
  { code: "no", label: "Norveççe" },
  { code: "fi", label: "Fince" },
  { code: "el", label: "Yunanca" },
  { code: "he", label: "İbranice" },
  { code: "cs", label: "Çekçe" },
  { code: "ro", label: "Romence" },
  { code: "hu", label: "Macarca" },
];
